### ISSUE TITLE
App not starting

### ISSUE THREAD

**Issue by DaliJarboui** [starstorms9/geco#15]
the link provided do not work

**Comment by dhimmel** [comment]
When I go to https://share.streamlit.io/starstorms9/geco/master/geco_app.py/+/ (which I discovered via the [streamlit gallery](https://streamlit.io/gallery?type=apps&category=science-technology)), I get

> Oh no.
Error running app. If this keeps happening, please file an issue.

Assuming this is the same issue that @DaliJarboui is reporting.

**Comment by starstorms9** [comment]
App required a quick reboot but is working as normal now, thanks!
