### ISSUE TITLE
link to publication

### ISSUE THREAD

**Issue by habowski** [starstorms9/geco#19]
Link to published manuscript 
https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-020-03951-2

Citation: 
Habowski, A.N., T.J. Habowski, and M.L. Waterman. (2021) GECO: Gene expression clustering optimization app for non-linear data visualization of patterns. BMC Bioinformatics, 22:29. DOI: 10.1186/s12859-020-03951-2.

**Comment by starstorms9** [comment]
Link added in the main description.
