### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by 84AP** [starstorms9/geco#24]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://starstorms9-geco-geco-app-y9v04r.streamlit.app/starstorms9/geco/geco_app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by starstorms9** [comment]
This is caused when too much data is uploaded at once, it happens occasionally but is only temporary.
